# Generated by Django 5.0.7 on 2025-02-22 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Area Encargada')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Area-Grupo',
                'verbose_name_plural': 'AREAS-Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('contenido', models.TextField()),
                ('archivo', models.FileField(upload_to='inicio')),
                ('tipo', models.CharField(choices=[('MP4', 'Video'), ('JPG', 'Foto-Imagen'), ('MP3', 'Musica-Sonido'), ('PDF', 'Documento Pdf')], max_length=3)),
                ('enlace', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmcvweb.grupo', verbose_name='Area Encargada')),
            ],
            options={
                'verbose_name': 'Bienvenida',
                'verbose_name_plural': 'Bienvenidas',
                'ordering': ['updated'],
            },
        ),
    ]
